Feat/mr 18
mctekk/mcbrand pull request #16
Opened 2023-10-16 16:42 UTC by Arzoid29

2023-10-17 12:00 UTC, code-bryan requested changes

2023-10-17 12:00 UTC, brya0x commented on src/components/atoms/animations/index.ts
> +}
**Change**: this is not an atom you can move it to interactions/types

2023-10-17 12:00 UTC, brya0x commented on src/components/atoms/step-button/index.tsx
> +  };
**Change**: instead of using methods like this use useMemo

2023-10-17 12:00 UTC, brya0x commented on src/components/atoms/step-button/index.tsx
> +    </div>
**Question**: honestly I don't see the point of this component. what happens if i have step 4? Is not reusing anything is kinda weird to watch

2023-10-17 12:00 UTC, brya0x commented on src/components/organism/sections/why-sales-assist/complete-sales-painless/index.tsx
> +            data.bullet_points.map((k) => {
**Change**: do not use characters to explore inside a map it breaks clean code use a word that says what are you doing here

2023-10-17 12:00 UTC, brya0x commented on src/components/organism/sections/why-sales-assist/how-it-works/index.tsx
> +          {data.actions.map((k, i) => {
**Change**: same thing here

2023-10-17 12:00 UTC, brya0x commented on src/components/organism/sections/why-sales-assist/simplify-sales/index.tsx
> +            >
**Refactor**: create a method to handle this instead of doing it here

2023-10-17 12:00 UTC, brya0x commented on src/components/organism/sections/why-sales-assist/simplify-sales/index.tsx
> +              {data.show_case.map((d, i) => (
**Change**: omg

2023-10-17 12:00 UTC, brya0x commented on src/model/interactions/use-progress/index.ts
> +                setProgress(interval)
**Question**: i keep asking myself the same thing are you using 4 or 2 spaces?

2023-10-18 13:00 UTC, code-bryan approved these changes

2023-10-18 13:00 UTC, code-bryan commented on src/components/atoms/step-button/index.tsx
> +console.log(currentStep)
console.log

2023-10-18 13:01 UTC, merged